#this is the comment line
name: name of the workflow
env:
  workflow_var: "workflowvalue"
 #this is the comment line kiran: ${{ vars.VEER_CLASS }}
  
on:
  push:
      branches: [ 'main' ]
jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      job_var: "this is the job variable"
    steps:
      - name: this is the first step
        run: |
           echo "$workflow_var, is the output ,getting the output "
           echo "$job_var "
      - name: this the second step
        run: 
          echo "veer="gitclass" >> $GITHUB_ENV" 
          echo  "this is the step level var $veer"

      - name: repo level var
        run:
          echo "repo level vars ${{ vars.VEER_CLASS }}

      # - name: assiging repo level var into global level
      #   run: 
      #      echo "calling repo var into glboal level  $kiran" 
