#this is the comment line
name: name of the workflow
on:
  push:
      branches: [ 'main' ]
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: this is the first step
        run: echo "hi welcome to the class"
